# Generated by Django 5.2.6 on 2026-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
