# Generated by Django 5.2.6 on 2026-05-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='skills',
            field=models.ManyToManyField(to='core.skill'),
        ),
    ]
