# Generated by Django 5.2.6 on 2026-05-13 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_skill_role_role_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='role',
            field=models.CharField(default='timezone.now', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='score',
            field=models.FloatField(),
        ),
    ]
