# Generated by Django 5.2.6 on 2026-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interviewresult_created_at_interviewresult_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
