# Generated by Django 5.2.6 on 2026-06-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_interviewresult_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
